{{- if and .Values.systemProbe.enabled .Values.daemonset.useDedicatedContainers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: system-probe-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    service: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
    chart_name: {{ $.Chart.Name }}
    heritage: {{ .Release.Service | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: "{{ template "datadog.fullname" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  system-probe.yaml: |
    system_probe_config:
      enabled: {{ $.Values.systemProbe.enabled }}
      debug_port:  {{ $.Values.systemProbe.debugPort }}
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
      enable_conntrack : {{ $.Values.systemProbe.enableConntrack }}
      bpf_debug: {{ $.Values.systemProbe.bpfDebug }}
{{- end }}
